metadata.format.version = "1.1"

[versions]

shadow = "9.3.1"
log4j2 = "2.25.3"
configurate = "4.2.0"
blossom = "2.2.0"
velocity = "3.4.0"
runtask = "3.0.2"
paper = "1.20.1-R0.1-SNAPSHOT"
sponge-api = "8.2.0"
sponge-gradle = "2.3.0"
plugin-yml = "0.6.0"
kotlin = "2.3.10"

[libraries]

log4j2 = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2" }
configurate = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

#Gradle dependencies
plugin-shadow = { group = "com.gradleup.shadow", name = "com.gradleup.shadow.gradle.plugin", version.ref = "shadow" }
plugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
sponge-gradle = { id = "org.spongepowered.gradle.plugin", version.ref = "sponge-gradle" }

# Run Task
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }

# Plugin-yml
pluginyml-paper = { id = "net.minecrell.plugin-yml.paper", version.ref = "plugin-yml" }

kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.4" }
